# All of these controllers were generated by the scaffold when we first set up the application
class SecretsController < ApplicationController
  before_action :set_secret, only: [:show, :edit, :update, :destroy]

  def home
  end

  # GET /secrets
  # GET /secrets.json
  def index
    # If the request was HTML, this will load app/views/secrets/index.html.erb
    # If the request was JSON, this will load app/views/secrets/index.json.jbuilder (which creates all of the JSON that all AJAX applications use, including Backbone apps)
    # Go to localhost:3000/secrets to see the HTML version
    # Go to localhost:3000/secrets.json to see the JSON version
    @secrets = Secret.all
  end

  # GET /secrets/1
  # GET /secrets/1.json
  def show
    # If the request was HTML, this will load app/views/secrets/show.html.erb
    # If the request was JSON, this will load app/views/secrets/show.json.jbuilder (which creates all of the JSON that all AJAX applications use, including Backbone apps)
    # Go to something like localhost:3000/secrets/1 to see the HTML version
    # Go to something like localhost:3000/secrets/1.json to see the JSON version
  end

  # GET /secrets/new
  def new
    @secret = Secret.new
  end

  # GET /secrets/1/edit
  def edit
  end

  # POST /secrets
  # POST /secrets.json
  def create
    @secret = Secret.new(secret_params)

    respond_to do |format|
      if @secret.save
        format.html { redirect_to @secret, notice: 'Secret was successfully created.' }
        format.json { render :show, status: :created, location: @secret }
      else
        format.html { render :new }
        format.json { render json: @secret.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secrets/1
  # PATCH/PUT /secrets/1.json
  def update
    respond_to do |format|
      if @secret.update(secret_params)
        format.html { redirect_to @secret, notice: 'Secret was successfully updated.' }
        format.json { render :show, status: :ok, location: @secret }
      else
        format.html { render :edit }
        format.json { render json: @secret.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secrets/1
  # DELETE /secrets/1.json
  def destroy
    @secret.destroy
    respond_to do |format|
      format.html { redirect_to secrets_url, notice: 'Secret was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secret
      @secret = Secret.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secret_params
      params.require(:secret).permit(:content)
    end
end
